  //car object
  car = {
    make: "toyota",
    model: "prius",
    exteriorColor: "white",
    interiorColor: "black",
    engineType: "4-Cyl, Hybrid, 1.8 Liter",
    transmission: 'Automatic, CVT',
    doors: '4 Door Hatchback',
    mpg: '54 City / 50 Hwy',
    drivetrain: "FWD",
    vin:"JTDKARFU0G3010153",
    briefDescription: 'Four Touring Hatchback 4D',
    description: 'data goes here',
    notes: 'notes goes here',
    windowSticker: 'https://windowsticker.carvana.io/MonroneyWsSpider_WS_id811f7f50-b214-11ea-b8dc-06db4edf06e7.pdf',
    numberOfKeys: 2,
    year: 2016,
    dateListedForSale: 06302020,
    dateSold: 0,
    salesPrice: 19900,
    miles: 24853,
    stock: 2000594302,
    vehicleId: 1465978,
    modification: [],
    exteriorPhotos: ['file1.jpg','file2.png','file3.jpg','file4.png'],
    interiorPhotos: ['file1.jpg','file2.png','file3.jpg','file4.png'],
    highlights: {
      gasSavings:'Expect to save money at the fuel pump! This vehicle is ranked in the top 15% on Carvana in MPGs for its body type',
      accidentFree:'Like every Carvana vehicle, this vehicle has never been in a reported accident.',
      keepMovingPrice:'This car is priced at least $1,500 below its Kelley Blue Book® Suggested Retail Value.',
      carFax:'link'
    },
    stereo: {
      bluetooth: false,
      aux: true,
      radio:true
    },
    features: {
        sunroof: false,
        powerWindows: true,
        airbags: true,
        childLocks: true,
        seatWarmers: false,
        installedPackages: [
          {preferredAccessoryPackage: 'Rear Bumper Applique, Cargo Net (PPO), Carpet Floor Mats & Cargo Mat'},
          'Prius Four Touring Package',
          'Lower Console/Shifter Applique Package'
        ],
        installedOptions: ['Special Color'],
        standardEquipment: [
          'Airbag Occupancy Sensor',
          'Driver Knee Airbag and Passenger Cushion Front Airbag',
          'Rear Child Safety Locks',
          'Outboard Front Lap And Shoulder Safety Belts includes: Rear Center 3 Point, Height Adjusters and Pretensioners',
          'Back-Up Camera',
          'Wheels: 7J x 17" 5-Spoke Aluminum Alloy',
          'Tires: P215/45R17 AS',
          'Body-Colored Front Bumper',
          'Front Fog Lamps',
          'SofTex Seat Trim includes: w/blue contrast stitching',
          'Forward Collision Mitigation and Rear Collision Warning',
          'Lane Keeping Assist',
          'Lane Departure Warning',
          'Multi-Link Rear Suspension w/Coil Springs',
          'Black Side Windows Trim and Black Front Windshield Trim',
          'Programmable Projector Beam Led Low/High Beam Auto High-Beam Daytime Running Lights Preference Setting Headlamps w/Delay-Off',
          'Distance Pacing w/Traffic Stop-Go',
          'Interior Trim includes: Metal-Look/Piano Black Instrument Panel Insert, Piano Black Door Panel Insert, Colored Console Insert and Chrome/Metal-Look Interior Accents',
          'Urethane Gear Shifter Material',
          'Roll-Up Cargo Cover',
          'Curtain 1st And 2nd Row Airbags',
          'Dual Stage Driver And Passenger Front Airbags',
          'Low Tire Pressure Warning',
          'Dual Stage Driver And Passenger Seat-Mounted Side Airbags',
          'Side Impact Beams',
          'ABS And Driveline Traction Control',
          'Electronic Stability Control',
          'Air Filtration SAFETY',
          '2 12V DC Power Outlets',
          '2 Seatback Storage Pockets',
          'Front Center Armrest and Rear Center Armrest',
          'Manual Adjustable Front Head Restraints and Manual Adjustable Rear Head Restraints',
          'Seats w/Leatherette Back Material',
          'Digital Display',
          'Outside Temp Gauge',
          'Trip Computer',
          'Systems Monitor',
          'Power Door Locks w/Autolock Feature',
          'Delayed Accessory Power',
          'Power 1st Row Windows w/Front And Rear 1-Touch Up/Dowm',
          'Driver And Passenger Door Bins',
          'Garage Opener',
          'Lane Change Assist',
          'Cargo Space Lights',
          'Cargo Area Concealed Storage',
          'Carpet Floor Trim',
          'Full Carpet Floor Covering',
          'Fade-To-Off Interior Lighting',
          'Front Map Lights',
          'Full Floor Console w/Covered Storage, Mini Overhead Console w/Storage and 2 12V DC Power Outlets',
          'Driver And Passenger Visor Vanity Mirrors w/Driver And Passenger Illumination',
          'Day-Night Rearview Mirror',
          'Full Cloth Headliner',
          'Driver Foot Rest',
          'Illuminated Glove Box',
          'HVAC includes: Underseat Ducts',
          'Automatic Air Conditioning',
          'Cruise Control w/Steering Wheel Controls',
          'Remote Releases -Inc: Power Fuel',
          'Remote Keyless Entry w/Integrated Key Transmitter, 2 Door Curb/Courtesy, Illuminated Entry, Illuminated Ignition Switch and Panic Button',
          'Proximity Key For Doors And Push Button Start',
          'Rear Cupholder',
          'Front Cupholder',
          'Leatherette Steering Wheel',
          'Power Rear Windows',
          'Gauges includes: Speedometer, Odometer, Traction Battery Level, Power/Regen, Trip Odometer and Trip Computer',
          'Manual Tilt/Telescoping Steering Column',
          '60-40 Folding Bench Front Facing Fold Forward Seatback Rear Seat',
          'Passenger Seat',
          'Driver Seat',
          'Heated Front Bucket Seats includes: seatback pockets, 8- way adjustable drivers seat w/power lumbar support and 4-way adjustable front passenger seat',
          '3 LCD Monitors In The Front',
          'Integrated Roof Antenna',
          'Radio w/Seek-Scan, MP3 Player, Clock, Speed Compensated Volume Control and Steering Wheel Controls',
          'Radio Entune Premium Audio Navigation App Suite includes the Entune Multimedia Bundle, 7 inch high resolution touch-screen w/split screen display, AM/FM CD player, 6 speakers, auxiliary audio jack, USB 2.0 port w/iPod connectivity and control, advanced voice recognition, hands-free phone capability, phone book access and music streaming via Bluetooth wireless technology, Siri Eyes Free, Entune App Suite , HD Radio, HD predictive traffic and doppler weather overlay, AM/FM cache radio', 'SiriusXM All Access Radio w/3-month complimentary trial and Gracenotes album cover art Access to Entune services is subscription free. See toyota.com/entune for details.',
          'LED Brakelights',
          'Tailgate/Rear Door Lock Included w/Power Door Locks',
          'Liftgate Rear Cargo Access',
          'Front License Plate Bracket',
          'Black Grille',
          'Galvanized Steel and Aluminum Panels',
          'Rain Detecting Variable Intermittent Wipers',
          'Light Tinted Glass',
          'Fixed Rear Window w/Fixed Interval Wiper and Defroster',
          'Body-Colored Power Heated Side Mirrors w/Manual Folding',
          'Body-Colored Door Handles',
          'Body-Colored Rear Bumper w/Black Rub Strip/Fascia Accent',
          'Clearcoat Paint',
          'Repair Kit Spare Tire',
          'Lithium Ion Traction Battery',
          'Regenerative 4-Wheel Disc Brakes w/4-Wheel ABS, Front Vented Discs, Brake Assist and Hill Hold Control',
          'Strut Front Suspension w/Coil Springs',
          'Single Stainless Steel Exhaust',
          '11.3 Gal. Fuel Tank',
          'Electric Power-Assist Steering',
          'Front And Rear Anti-Roll Bars',
          'Gas-Pressurized Shock Absorbers',
          'Hybrid Electric Motor',
          'Battery w/Run Down Protection',
          '4.11 Axle Ratio',
          'Front-Wheel Drive',
          'Please Note: The equipment listed above is the configuration of the vehicle as originally sold. Items such as XM and other service subscriptions, original tires, and removable accessories (such as cargo nets) are unlikely to still be on the vehicle.'
        ]
       }
    }
